### ISSUE TITLE
Link too long in plugin description

### ISSUE THREAD

**Issue by Drasli-Tana** [MidnightPlugins/Logbook-Help#1]
As you can see in this screenshot, the link to this github repo is too long for the ingame description.
![image](https://user-images.githubusercontent.com/100795666/221295954-74b858e7-aee2-4b4f-890c-ddb3a6822114.png)

I am using the continous build, 0.10.0-alpha, commit C82810A on a windows 10 pro machine with the latest release of this plugin, both in windowed and fullscreen mode. 
If the problem comes from the game itself, let me know and I'll fill an issue there.

**Comment by MidnightPlugins** [comment]
Yes, I believe that would be an issue with the vanilla plugin screen.

Thanks for trying out my plugin!
